version: '3'

services: 
  next:
    build: .
    container_name: next
    env_file:
      - ./env/next.env
    ports:
      - "8000:8000"
    restart: always
    links:
      - express-postgres

  express-postgres:
    image: shintech/express-postgres:latest
    container_name: express-postgres
    env_file:
      - ./env/express.env
    restart: always
    links:
      - postgres

  postgres:
    image: shintech/blog-database:latest
    container_name: postgres
    env_file:
        - ./env/postgres.env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always

  express-elastic:
    image: shintech/express-elastic:latest
    container_name: express-elastic
    env_file:
      - ./env/express.env
    restart: always
    links:
      - elastic

  elastic:
    image: elasticsearch:latest
    container_name: elasticsearch
    env_file:
        - ./env/elastic.env
    restart: always
    # volumes:
    #   - esdata1:/usr/share/elasticsearch/data

  express-mongo:
    image: shintech/express-mongo:latest
    container_name: express-mongo
    env_file:
      - ./env/express.env
    restart: always
    links:
      - mongo
      
  mongo:
    container_name: mongo
    image: shintech/shintech-mongo:latest
    env_file:
        - ./env/mongo.env
    volumes:
      - ./data/mongo:/data/db
    restart: always
