version: '3'

services: 
  next:
    build: .
    image: shintech/next
    container_name: next
    network_mode: bridge
    env_file:
      - ./next.env
    links:
      - postgres
    ports:
      - "8000:8000"
    restart: always
    
  postgres:
    image: shintech/blog-database
    build: ./database
    container_name: postgres
    network_mode: bridge
    env_file:
        - ./postgres.env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always