version: '3'

services: 
  next:
    build: .
    image: shintech/next:latest
    container_name: next
    env_file:
      - ./next.env
    ports:
      - "8000:8000"
    restart: always
    links:
      - express-postgres

  express-postgres:
    image: shintech/express-postgres:latest
    container_name: express-postgres
    env_file:
      - ./express.env
    restart: always
    links:
      - postgres

  postgres:
    image: shintech/blog-database:latest
    container_name: postgres
    env_file:
        - ./postgres.env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always
