const constants = {
  FETCH_POST: 'FETCH_POST',
  FETCH_POSTS: 'FETCH_POSTS',
  INCREMENT: 'INCREMENT',
  CHANGE_MENU_VALUE: 'CHANGE_MENU_VALUE',
  FETCH_DEVICES: 'FETCH_DEVICES',
  SEARCH_INVENTORY: 'SEARCH_INVENTORY',
  FETCH_USER: 'FETCH_USER',
  FETCH_USERS: 'FETCH_USERS'
}

export default constants
