const constants = {
  INCREMENT: 'INCREMENT',
  FETCH_DEVICES_BEGIN: 'FETCH_DEVICES_BEGIN',
  FETCH_DEVICES_SUCCESS: 'FETCH_DEVICES_SUCCESS',
  FETCH_DEVICES_ERROR: 'FETCH_DEVICES_ERROR',
  TOGGLE_MODAL: 'TOGGLE_MODAL',
  ADD_DEVICE: 'ADD_DEVICE',
  ADD_DEVICE_SUCCESS: 'ADD_DEVICE_SUCCESS',
  ADD_DEVICE_ERROR: 'ADD_DEVICE_ERROR',
  CHANGE_PAGE: 'CHANGE_PAGE'
}

export default constants
