const constants = {
  INCREMENT: 'INCREMENT',

  FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',
  FETCH_POSTS_ERROR: 'FETCH_POSTS_ERROR',

  FETCH_POST: 'FETCH_POST',
  ADD_POST: 'ADD_POST',

  FETCH_GRAPH: 'FETCH_GRAPH',

  FETCH_TASKS: 'FETCH_TASKS',
  ADD_TASK: 'ADD_TASK',

  SEND_FILE: 'SEND_FILE'
}

export default constants
