const constants = {
  INCREMENT: 'INCREMENT',

  TOGGLE_MODAL: 'TOGGLE_MODAL',

  FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',
  FETCH_POSTS_ERROR: 'FETCH_POSTS_ERROR',

  CHANGE_MENU: 'CHANGE_MENU',

  FETCH_POST: 'FETCH_POST',
  ADD_POST: 'ADD_POST',

  FETCH_GRAPH: 'FETCH_GRAPH',

  FETCH_TASKS: 'FETCH_TASKS',
  ADD_TASK: 'ADD_TASK',

  SEND_FILE: 'SEND_FILE',

  SEARCH_DEVICES: 'SEARCH_DEVICES',
  FETCH_DEVICES: 'FETCH_DEVICES',

  ADD_DEVICE_SUCCESS: 'ADD_DEVICE_SUCCESS',
  ADD_DEVICE_ERROR: 'ADD_DEVICE_ERROR'
}

export default constants
